import { Location } from "../location";
export const LOCATIONS: Location[] = [
  {index: 0, name: "Споменик „Петре Прличко“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 20, extra: ""},
  {index: 1, name: "Споменик Јустинјан Први", link: "https://maps.app.goo.gl/9hJkT5QTFd5QwNbg6", challenge: "Се земаат ист број на гранки како и бројот на учесници во тимот и сите позираат еден до друг држејќи ги гранките на ист начин како што Јустинјан го држи стапот со знамето.", points: 20, extra: ""},
  {index: 2, name: "Споменик на „Гоце Делчев“", link: "https://maps.app.goo.gl/1cjvb9EmDRAjYpP67", challenge: "Да се остави цвеќе на споменикот и сите членови на групата да се сликаат со споменикот и цвеќето.", points: 20, extra: ""},
  {index: 3, name: "Споменик на „Даме Груев“", link: "https://maps.app.goo.gl/GFxvMGxnSR24zr2C6", challenge: "Да се изрецитира некоја народна песна или да се испее.", points: 25, extra: ""},
  {index: 4, name: "Делфина", link: "https://maps.app.goo.gl/eD4pS4JZSbTAtDZR9", challenge: "Сите учесници се местат на скалите во некои позиции кои наликуваат на пливање и се запазува статуата на Делфина да се гледа во позадина.", points: 25, extra: ""},
  {index: 5, name: "Споменик „Александар III Македонски“", link: "https://maps.app.goo.gl/yfX8CdwkxiCQTJhp7", challenge: "Сите учесници се сликаат така што секој од нив се гледа на сликата до еден од лавовите-за секој учесник посебен лав.", points: 20, extra: ""},
  {index: 6, name: "Споменик „Димитрија Чуповски“", link: "https://maps.app.goo.gl/rWukYzVzp4aBgfYZA", challenge: "Секој од учесниците зема нешто налик на книга(тетратка, лист...) и се сликаат сите заедно пред самиот споменик.", points: 20, extra: ""},
  {index: 7, name: "Шчипските свадбари", link: "https://maps.app.goo.gl/jDcwp7QuZ2bLE67d6", challenge: "Секој од учесниците позира како еден од музикантите.", points: 25, extra: "Ако некој има вискински инструмент. 30"},
  {index: 8, name: "Споменик „Павел Шатев“", link: "https://maps.app.goo.gl/zyYdJDfNE6HXcwq26", challenge: "Еден од учесниците пробува да седне во воздух.", points: 20, extra: "А ако има уште некој што сака да седне на него. 20"},
  {index: 9, name: "Порта „Македонија“", link: "https://maps.app.goo.gl/h3frLLDg21c27pZh7", challenge: "Сите учесници се сликаат на тој начин што изгледа како ја да држат портата, портата треба да е далеку а тие пред камерата.", points: 25, extra: ""},
  {index: 10, name: "Споменик „Методија Андонов - Ченто“", link: "https://maps.app.goo.gl/sAhLB5XUf34YB9wx6", challenge: "Сите учесници се местат пред споменикот и позираат со капата како што е самиот споменик направен.", points: 15, extra: ""},
  {index: 11, name: "Споменик „Президиум на АСНОМ“", link: "https://maps.app.goo.gl/zphXrWLbfXoCkyHSA", challenge: "Двајца учесници стојат еден до друг, едниот подава нешто налик на книга со едната рака, а другиот се поздравува со другата рака.", points: 15, extra: ""},
  {index: 12, name: "Мост на уметноста", link: "https://maps.app.goo.gl/VGx7Da7BCyCcqCkM7", challenge: "Еден учесник стои до споменикот на Тоше Проески и пее една негова песна по негов избор имитирајќи дека има микрофон.", points: 25, extra: ""},
  {index: 13, name: "Бронзен споменик „Голем Бик“", link: "https://maps.app.goo.gl/fZnijo6f3jemWs8Y9", challenge: "Сите учесници се држат за бикот, на роговите и слично, како да се борат со него.", points: 20, extra: ""},
  {index: 14, name: "Споменик „Питу Гули“", link: "https://maps.app.goo.gl/iDoohwcenh2vghEU7", challenge: "Сите учесници треба да најдат клупа, камен или нешто во позадина и тој што слика да ги слика сите нив и целата статуа да се гледа во кадар (за секој учесник по еден објект за седење).", points: 15, extra: "dasdsa"},
  {index: 15, name: "?", link: "https://maps.app.goo.gl/BjWF7NGNPWphYHzX9", challenge: "За овој предизвик ми е потребно повеќе инфо...", points: 20, extra: ""}
]
