import { Location } from "../location";
export const LOCATIONS: Location[] = [
  {index: 0, name: "Споменик „Петре Прличко“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 20, extra: ""},
  {index: 1, name: "Споменик Јустинјан Први", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 20, extra: ""},
  {index: 2, name: "Споменик на „Гоце Делчев“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 20, extra: ""},
  {index: 3, name: "Споменик на „Даме Груев“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 25, extra: ""},
  {index: 4, name: "Делфина", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 25, extra: ""},
  {index: 5, name: "Споменик „Александар III Македонски“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 20, extra: ""},
  {index: 6, name: "Споменик „Димитрија Чуповски“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 20, extra: ""},
  {index: 7, name: "Шчипските свадбари", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 25, extra: ""},
  {index: 8, name: "Споменик „Павел Шатев“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 20, extra: ""},
  {index: 9, name: "Порта „Македонија“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 25, extra: ""},
  {index: 10, name: "Споменик „Методија Андонов - Ченто“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 15, extra: ""},
  {index: 11, name: "Споменик „Президиум на АСНОМ“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 15, extra: ""},
  {index: 12, name: "Мост на уметноста", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 25, extra: ""},
  {index: 13, name: "Бронзен споменик „Голем Бик“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 20, extra: ""},
  {index: 14, name: "Споменик „Питу Гули“", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 15, extra: "dasdsa"},
  {index: 15, name: "?", link: "https://maps.app.goo.gl/vUhV8quzh3t7FKLi8", challenge: "Двајца учесници во тимот се сликаат на тој начин што едниот стои под капата, а другиот се поздравува со Петре.", points: 20, extra: "dasdas"}
]
